### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by madcoda9000** [fedi-dayeg/complete-nestjs-boilerplate#1]
Hello,

i just want to say, great work so far! And many thanks for publishing that. To me (and maybe other developers) it would be very helpful when the single endpoints are documented a bit more in detail. Or maybe a simple react client app, which makes use of this boilerplate backend.

Anyway, many thanks for that.

Whish you All the best
Sascha

**Comment by fedi-dayeg** [comment]
Hello,
Thank you for your contribution,
yeah sure i will do good documentation in each API very soon,
for the React client, it may be later (at the end of the year).
